version: "2.3"

services:
  covid:
    build: .
    #image: coffeespiller/prom101:latest
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:8.3.4
    volumes:
      - ./grafana_boards:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.13.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml

  mongo:
    image: mongo:4