{
 "title": "COVID GDG Prometheus 101",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New Cases Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gdg_new_cases_total{}[1m])"
    }
   ]
  },
  {
   "title": "Total Cases",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "gdg_new_cases_total{}" }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gdg_new_recovery_total{}[1m])"
    }
   ]
  },
  {
   "title": "Recovered Cases",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "gdg_new_recovery_total{}" }
   ]
  },
  {
   "title": "Active Cases",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    { "expr": "gdg_active_cases" }
   ]
  },
  {
   "title": "Cases Ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "gdg_new_recovery_total{}/gdg_new_cases_total{} * 100"
    }
   ]
  }
 ]
}